# Generated by Django 4.2.21 on 2026-08-27 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_complaint_complaintstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="category_detected_automatically",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="category_detection_confidence",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="complaint",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="A likely pre-existing complaint covering the same issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_reports",
                to="core.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Allow other campus users to find and support this issue without seeing reporter details.",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority_score",
            field=models.PositiveSmallIntegerField(
                default=50, help_text="Rule-based urgency score from 0 to 100."
            ),
        ),
        migrations.CreateModel(
            name="ComplaintSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports",
                        to="core.complaint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supported_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="complaintsupport",
            constraint=models.UniqueConstraint(
                fields=("complaint", "user"), name="unique_complaint_support_per_user"
            ),
        ),
    ]
