# Generated by Django 4.2.30 on 2026-09-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_direct_student_reporting'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complaintsupport',
            name='unique_complaint_support_per_user',
        ),
        migrations.AddField(
            model_name='complaintsupport',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='complaintsupport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='complaintsupport',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('complaint', 'user'), name='unique_complaint_support_per_user'),
        ),
        migrations.AddConstraint(
            model_name='complaintsupport',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('complaint', 'session_key'), name='unique_complaint_support_per_session'),
        ),
    ]
