# Generated by Django 4.2.30 on 2026-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0007_remove_complaintsupport_unique_complaint_support_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hall_location",
            field=models.CharField(
                blank=True,
                help_text="Assigned hall or facility (from staff roster).",
                max_length=200,
            ),
        ),
    ]
