# Generated by Django 4.2.30 on 2026-09-25 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_unique_task_tokens(apps, schema_editor):
    Complaint = apps.get_model("core", "Complaint")
    for complaint in Complaint.objects.all():
        complaint.staff_task_token = uuid.uuid4()
        complaint.save(update_fields=["staff_task_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_hall_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='core.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_proof',
            field=models.ImageField(blank=True, null=True, upload_to='reopen_proofs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_proofs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff_task_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_unique_task_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='staff_task_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountability_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_provosts', to='core.building'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_hods', to='core.department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('registrar', 'Registrar'), ('provost', 'Provost'), ('hod', 'Head of Department'), ('staff', 'Maintenance staff'), ('student', 'Student'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
