# Generated by Django 4.2.30 on 2026-09-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_building_department_complaint_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_type",
            field=models.CharField(
                default="hall",
                help_text="e.g. hall, hostel, academic, administrative",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="capacity_detail",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="building",
            name="gender",
            field=models.CharField(
                blank=True, help_text="e.g. Boys, Girls, Co-ed", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostels",
                to="core.building",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Constituent hostel / block short name",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="wing_detail",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="building",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
