# Generated by Django 4.2.30 on 2026-09-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_building_building_type_building_capacity_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS Latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS Longitude",
                max_digits=9,
                null=True,
            ),
        ),
    ]
