# Generated by Django 4.2.30 on 2026-09-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_building_latitude_building_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In progress"),
                    ("resolved", "Resolved"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["status", "-created_at"], name="complaint_stat_creat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["priority", "status"], name="complaint_prio_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["category", "status"], name="complaint_cat_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["-created_at"], name="complaint_created_at_idx"),
        ),
    ]
